### ISSUE TITLE
Feedback for “How It Works”

### ISSUE THREAD

**Issue by thestuntman** [Azwedo/goatslider-docs#25]
I follow all steps, everything's fine. I Create, and it says to paste into Webflow Designer... where? How? What? There is no way to paste into Designer. There is nothing on my clipboard. There is no Paste option available. I am in a nice empty Section with a Container and Div ready to go, but nothing happens. I try pasting as normal and again, nothing on the clipboard. It feels like you've left out the only steps that really matter and jump right past the one thing people need to know.

**Comment by bfzli** [comment]
We have added video documentation to this page. We hope this fixes the issues and clarifies the concepts of the Goat Slider app and how to use it.

Did it solve your issue?
